### ISSUE TITLE
First mockpus of the DDI

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/specifications#1]
This are the first Mockups of the DDI Pilot Project:

  - DDI Browser 
   
   <img src="https://raw.githubusercontent.com/PSI-PROXI/datadiscoveryindex/master/docs/DDI-Browser.png"/>
 
  - DDI Front Page 

  <img src="https://raw.githubusercontent.com/PSI-PROXI/datadiscoveryindex/master/docs/DDI-Home.png"/>

  - DDI Front Page 

  <img src="https://raw.githubusercontent.com/PSI-PROXI/datadiscoveryindex/master/docs/DDI-Dataset.png"/>

**Comment by ypriverol** [comment]
@baimingze we should have a final definition about the way we will show this information, I'm now working on a possible visualisation mockup.

**Comment by ypriverol** [comment]
some interesting examples:
  - https://grokker.com/
  - http://mashable.com/2007/05/15/16-awesome-data-visualization-tools/
  - http://www.google.com/trends/

**Comment by baimingze** [comment]
Yes, they are beautiful!

**Comment by ypriverol** [comment]
- http://www.visualizing.org/full-screen/46075
- http://visualization.geblogs.com/visualization/hmchallenge/
- http://visualization.geblogs.com/visualization/network/

**Comment by ypriverol** [comment]
<img src="https://raw.githubusercontent.com/PSI-PROXI/datadiscoveryindex/master/docs/DDI%20Browser%20Home%20page.png" />
